### PR TITLE
_request() was a private API deprecated as of v0.11 of the sails.io.js

### PR DESCRIPTION
**Pull request by seth2810**

### CODE REVIEW

**Comment by robwormald** [comment]
thanks for this!

**Comment by tarlepp** [comment]
Version bump?

**Comment by robwormald** [comment]
Pretty sure this is on 0.11.2, but lmk if that's not the case and i'll
rebump

**Comment by tarlepp** [comment]
Yeah it's on master but ```0.11.2``` isn't out yet? https://github.com/balderdashy/angularSails/blob/master/package.json#L3 and https://github.com/balderdashy/angularSails/blob/master/bower.json#L3

**Pull request merged**
